// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHc4KWppT1uRCQ85EjXAWC5iBAB0hZM2s',
    appId: '1:767220545663:android:6faa1966ce70fa74e6e74a',
    messagingSenderId: '767220545663',
    projectId: 'pets-health-info',
    storageBucket: 'pets-health-info.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKB-KQv5Ir79Yq3dUpghSmkiezKSLeoYA',
    appId: '1:767220545663:ios:6bd372d4f56e387fe6e74a',
    messagingSenderId: '767220545663',
    projectId: 'pets-health-info',
    storageBucket: 'pets-health-info.firebasestorage.app',
    androidClientId: '767220545663-3phpv9hp0fa0htkr28a935s6h580rhma.apps.googleusercontent.com',
    iosClientId: '767220545663-cg8otkc754qd5tlnlskvrfohlbtaomuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFrontend',
  );
}
